# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'model.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 100, 800, 500))
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.cryptedPswView = QtWidgets.QTableView(self.tab1)
        self.cryptedPswView.setGeometry(QtCore.QRect(0, 0, 800, 331))
        self.cryptedPswView.setObjectName("cryptedPswView")
        self.labelDeleteRow = QtWidgets.QLabel(self.tab1)
        self.labelDeleteRow.setGeometry(QtCore.QRect(580, 340, 121, 16))
        self.labelDeleteRow.setObjectName("labelDeleteRow")
        self.deleteRowInput = QtWidgets.QLineEdit(self.tab1)
        self.deleteRowInput.setGeometry(QtCore.QRect(710, 340, 41, 21))
        self.deleteRowInput.setObjectName("deleteRowInput")
        self.pushButtonDeleteRow = QtWidgets.QPushButton(self.tab1)
        self.pushButtonDeleteRow.setGeometry(QtCore.QRect(760, 340, 21, 21))
        self.pushButtonDeleteRow.setObjectName("pushButtonDeleteRow")
        self.pushButtonSaveData = QtWidgets.QPushButton(self.tab1)
        self.pushButtonSaveData.setGeometry(QtCore.QRect(694, 410, 91, 21))
        self.pushButtonSaveData.setObjectName("pushButtonSaveData")
        self.lineEditSendKey = QtWidgets.QLineEdit(self.tab1)
        self.lineEditSendKey.setGeometry(QtCore.QRect(80, 350, 113, 20))
        self.lineEditSendKey.setObjectName("lineEditSendKey")
        self.lineEditSendIv = QtWidgets.QLineEdit(self.tab1)
        self.lineEditSendIv.setGeometry(QtCore.QRect(80, 380, 113, 20))
        self.lineEditSendIv.setObjectName("lineEditSendIv")
        self.labelSendKey = QtWidgets.QLabel(self.tab1)
        self.labelSendKey.setGeometry(QtCore.QRect(40, 350, 21, 16))
        self.labelSendKey.setObjectName("labelSendKey")
        self.labelSendIv = QtWidgets.QLabel(self.tab1)
        self.labelSendIv.setGeometry(QtCore.QRect(40, 380, 21, 16))
        self.labelSendIv.setObjectName("labelSendIv")
        self.pushButtonDecrypt = QtWidgets.QPushButton(self.tab1)
        self.pushButtonDecrypt.setGeometry(QtCore.QRect(140, 410, 51, 21))
        self.pushButtonDecrypt.setObjectName("pushButtonDecrypt")
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.insertDataButton = QtWidgets.QPushButton(self.tab2)
        self.insertDataButton.setGeometry(QtCore.QRect(550, 320, 75, 23))
        self.insertDataButton.setObjectName("insertDataButton")
        self.inputProvider = QtWidgets.QLineEdit(self.tab2)
        self.inputProvider.setGeometry(QtCore.QRect(120, 70, 241, 20))
        self.inputProvider.setObjectName("inputProvider")
        self.inputUsr = QtWidgets.QLineEdit(self.tab2)
        self.inputUsr.setGeometry(QtCore.QRect(120, 110, 241, 20))
        self.inputUsr.setObjectName("inputUsr")
        self.inputPsw = QtWidgets.QLineEdit(self.tab2)
        self.inputPsw.setGeometry(QtCore.QRect(120, 150, 241, 20))
        self.inputPsw.setObjectName("inputPsw")
        self.inputKey = QtWidgets.QLineEdit(self.tab2)
        self.inputKey.setGeometry(QtCore.QRect(120, 190, 241, 20))
        self.inputKey.setObjectName("inputKey")
        self.inputIv = QtWidgets.QLineEdit(self.tab2)
        self.inputIv.setGeometry(QtCore.QRect(120, 230, 241, 20))
        self.inputIv.setObjectName("inputIv")
        self.labelProvider = QtWidgets.QLabel(self.tab2)
        self.labelProvider.setGeometry(QtCore.QRect(10, 70, 81, 20))
        self.labelProvider.setObjectName("labelProvider")
        self.labelUsername = QtWidgets.QLabel(self.tab2)
        self.labelUsername.setGeometry(QtCore.QRect(10, 110, 81, 20))
        self.labelUsername.setObjectName("labelUsername")
        self.labelPassword = QtWidgets.QLabel(self.tab2)
        self.labelPassword.setGeometry(QtCore.QRect(10, 150, 81, 20))
        self.labelPassword.setObjectName("labelPassword")
        self.labelKey = QtWidgets.QLabel(self.tab2)
        self.labelKey.setGeometry(QtCore.QRect(10, 190, 81, 20))
        self.labelKey.setObjectName("labelKey")
        self.labelIv = QtWidgets.QLabel(self.tab2)
        self.labelIv.setGeometry(QtCore.QRect(10, 230, 81, 20))
        self.labelIv.setObjectName("labelIv")
        self.label = QtWidgets.QLabel(self.tab2)
        self.label.setGeometry(QtCore.QRect(370, 70, 16, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab2)
        self.label_2.setGeometry(QtCore.QRect(370, 110, 16, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab2)
        self.label_3.setGeometry(QtCore.QRect(370, 150, 16, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab2)
        self.label_4.setGeometry(QtCore.QRect(370, 190, 16, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab2)
        self.label_5.setGeometry(QtCore.QRect(560, 340, 91, 16))
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.tab2, "")
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")
        self.tabWidget.addTab(self.tab3, "")
        self.userList = QtWidgets.QComboBox(self.centralwidget)
        self.userList.setGeometry(QtCore.QRect(110, 20, 73, 22))
        self.userList.setObjectName("userList")
        self.labelUserSelected = QtWidgets.QLabel(self.centralwidget)
        self.labelUserSelected.setGeometry(QtCore.QRect(14, 20, 91, 20))
        self.labelUserSelected.setObjectName("labelUserSelected")
        self.labelPath = QtWidgets.QLabel(self.centralwidget)
        self.labelPath.setGeometry(QtCore.QRect(60, 50, 31, 20))
        self.labelPath.setObjectName("labelPath")
        self.path = QtWidgets.QLabel(self.centralwidget)
        self.path.setGeometry(QtCore.QRect(110, 50, 681, 20))
        self.path.setObjectName("path")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelDeleteRow.setText(_translate("MainWindow", "Delete row number:"))
        self.pushButtonDeleteRow.setText(_translate("MainWindow", "Ok"))
        self.pushButtonSaveData.setText(_translate("MainWindow", "Save changes"))
        self.labelSendKey.setText(_translate("MainWindow", "Key"))
        self.labelSendIv.setText(_translate("MainWindow", "Iv"))
        self.pushButtonDecrypt.setText(_translate("MainWindow", "Decrypt"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "Tab 1"))
        self.insertDataButton.setText(_translate("MainWindow", "PushButton"))
        self.labelProvider.setText(_translate("MainWindow", "Provider:"))
        self.labelUsername.setText(_translate("MainWindow", "Username:"))
        self.labelPassword.setText(_translate("MainWindow", "Password:"))
        self.labelKey.setText(_translate("MainWindow", "Encrypting key:"))
        self.labelIv.setText(_translate("MainWindow", "Encrypting iv:"))
        self.label.setText(_translate("MainWindow", "*"))
        self.label_2.setText(_translate("MainWindow", "*"))
        self.label_3.setText(_translate("MainWindow", "*"))
        self.label_4.setText(_translate("MainWindow", "*"))
        self.label_5.setText(_translate("MainWindow", "* Mandatory field"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "Tab 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), _translate("MainWindow", "Page"))
        self.labelUserSelected.setText(_translate("MainWindow", "User selected:"))
        self.labelPath.setText(_translate("MainWindow", "Path:"))
        self.path.setText(_translate("MainWindow", "path"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

